config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  resources :articles, only: [:index, :show]

  namespace :admin do
    resources :articles
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_images
  accepts_nested_attributes_for :article_images

  scope :order_by_descending, -> { order(entry_at: :desc) }
  scope :published, -> { where(published: true) }

  def default_images_build
    article_image_count = 5
    (article_image_count - article_images.count).times { article_images.build }
  end
end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  belongs_to :article
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create do
    #FiXME: 確認のため全て管理者権限
    self.admin = true
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_admin!

  protected
  def authenticate_admin!
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.order_by_descending
  end

  def show
  end

  def new
    @article = Article.new
    @article.default_images_build
  end

  def edit
    @article.default_images_build
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to [:admin, @article], notice: '記事を投稿しました。'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to [:admin, @article], notice: '記事を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_url, notice: '記事を削除しました。'
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:entry_at, :title, :content, :published, { article_images_attributes: [:id, :image] })
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.published.order_by_descending
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for [:admin, @article] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :entry_at
    = f.input :title
    = f.input :content
    = f.input :published

    = f.simple_fields_for :article_images do |img|
      - if img.object.image?
        .tag-sample= "挿入タグ：<img src='" + img.object.image.url + "' >"
        .uploaded-image= image_tag img.object.image.url
      = img.file_field :image

  .form-actions
    = f.button :submit

app/views/admin/articles/edit.html.haml
%h1 記事編集

= render 'form'

= link_to '詳細', admin_article_path(@article)
\|
= link_to '戻る', admin_articles_path

app/views/admin/articles/index.html.haml
%h1 記事一覧

%table.table.table-striped
  %thead
    %tr
      %th 投稿日
      %th タイトル
      %th 本文
      %th 公開有無
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= l article.entry_at
        %td= article.title
        %td= article.content.truncate(20, omission: '…')
        %td= article.published ? "公開" : "非公開"
        %td= link_to '詳細', admin_article_path(article)
        %td= link_to '編集', edit_admin_article_path(article)
        %td= link_to '削除', admin_article_path(article), method: :delete, data: { confirm: '削除してもよろしいですか?' }

%br

= link_to '新規投稿', new_admin_article_path

app/views/admin/articles/new.html.haml
%h1 新規投稿

= render 'form'

= link_to '戻る', admin_articles_path

app/views/admin/articles/show.html.haml
%p
  %b 投稿日:
  = l @article.entry_at
%p
  %b タイトル:
  = @article.title
%p
  %b 本文:
  = simple_format @article.content
%p
  %b 公開有無:
  = @article.published ? "公開" : "非公開"


= link_to '編集', edit_admin_article_path(@article)
\|
= link_to '戻る', admin_articles_path

app/views/articles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@article) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :entry_at
    = f.input :title
    = f.input :content

  .form-actions
    = f.button :submit

app/views/articles/_sidebar.html.haml
.sidebar
  .section
    %h3 プロフィール
    %strong 名前：しんくれあ
    %p 受託開発メインのIT企業に勤務するC#er。趣味は木工と読書です。
    %p これまでプライベートな日記がメインのブログでしたが、技術的な記事も書いていきたいと思います。

app/views/articles/index.html.haml
.col-md-9
  - @articles.each do |article|
    .article
      .entry_at
        = fa_icon('calender-o')
        = l article.entry_at
      %h2= article.title
      = simple_format article.content.truncate(100, omission: '…')
      = link_to '続きを読む', article

.col-md-3
  = render 'sidebar'

app/views/articles/show.html.haml
.col-md-9
  .article
    .entry_at
      = fa_icon('calender-o')
      = l @article.entry_at
    %h2= @article.title
    = simple_format @article.content

.col-md-3
  = render 'sidebar'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            .navbar-brand
              = link_to 'しんくれあ記', root_path
          .collapse.navbar-collapse
            %ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                %li
                  %p.navbar-text
                    Login as
                    %strong= current_user.email
                - if current_user.admin?
                  %li
                    = link_to '管理者画面', admin_articles_path
                %li
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete
              - else
                %li
                  = link_to '新規登録', new_user_registration_path
                %li
                  = link_to 'ログイン', new_user_session_path

    .main.container-fluid
      - if notice
        %p.notice= notice
      - if alert
        %p.alert= alert
      = yield

    %footer
      %p
        %small
          Copyright (C) 2018 sincrare All Rights Reserved.